name: Code Analysis

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  Quality:
    uses: TheDigitalSages/tds-github-actions/.github/workflows/CodeQuality.yml@main
    secrets: inherit
    with:
      project-dir: './src'