name: Frontend Testing
on:
  workflow_dispatch:
  pull_request:
jobs:
  single:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          config-file: cypress-config.js