name: Code Quality Scan

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  'Code Quality':
    uses: TheDigitalSages/tds-github-actions/.github/workflows/CodeQuality.yml@feature/actions
    secrets: inherit